### PR TITLE
DELETEing an already deleted asset responds with old asset value; expected MTConnectError

### PR DESCRIPTION
**Pull request by mnoomnoo**
[Issue 445](https://github.com/mtconnect/cppagent/issues/445)

### CODE REVIEW

**Comment by wsobel** [comment]
I don't think this is the correct behavior. If you're requesting an asset by id, you should be able to get it. We should discuss.

**Comment by robot-ranger** [comment]
when requesting an asset by asset id, how do we tell if that asset id had been previously deleted or not?

**Comment by robot-ranger** [comment]
oh, i see `removed="true"`. the issue is that is included in the response to a DELETE REST call, so it doesnt seem like there is a way to distinguish if the asset was deleted now because of my most recent DELETE or some previous action

**Comment by wsobel** [comment]
The Asset block has a removed property: https://model.mtconnect.org/#Diagrams___19_0_3_91b028d_1579531819046_475681_8369

In XML it will have something like

```xml
<CuttingTool removed="true" ....>
</CuttingTool>
```

**Comment by robot-ranger** [comment]
@mnoomnoo and i worked on this together but it can be closed. we had taken a more literal interpretation of REST delete function but if that is not MTConnect-canon then lets just close this.

**Pull request closed without merging**
