### PR TITLE
Add option for paths in a config file relative to config file

### PR DESCRIPTION
**Pull request by lorenzhaas**
Currently relative paths in the configuration file are resolved using the current directory or the one of the executable. When creating a "package" for machine deployment, however, containing the config file and all sorts of styles etc. one can't know where it is installed, where the actual executable is and from where the agent is started.

With the new option you can ship the config file with all other files and have proper path right from the beginning. The agent must only use the deployed config file, regardless where the agent is installed and from which folder it is started.

(Currently I do not have a Windows machine at hand, so that part is coded at best knowledge...)

### CODE REVIEW

**Comment by wsobel** [comment]
This change is complex enough it should have some tests. @lorenzhaas Can you write some tests to verify the functionality is correct?

Thanks,
Will Sobel

**Comment by lorenzhaas** [comment]
@wsobel I'll add tests the next days.

**Comment by lorenzhaas** [comment]
I had to expose "bool isFile()" from the agent. It seems to me the easiest solution to check if the path were set correctly. 
(Another easy option would be to make the test class a friend of Agent to access mFileMap directly, but I do not like that.)

**Comment by wsobel** [comment]
Merging this into the current main line. Somewhat complex since we made a lot of architectural changes.

**Comment by wsobel** [comment]
The agent has deviated too far/

**Pull request closed without merging**
