### PR TITLE
Adding json_printer.cpp to give JSON output for agent.

### PR DESCRIPTION
**Pull request by codenamesubho**

### CODE REVIEW

**Comment by wsobel** [comment]
Two questions before I can merge:

1. Did you write any tests?
2. Can the agent still generate XML?

Thanks,
Will

**Comment by Ghost-script** [comment]
@wsobel , tests need to be written yet. The xml_printer.cpp still has the XML generating functions but they are not being called anywhere.

**Comment by wsobel** [comment]
The agent needs to detect the response type by checking the Scripps accepts header. Prioritize xml over json.

**Comment by Ghost-script** [comment]
Hi @wsobel , i have updated the code. Now it gives output for XML/JSON depending on scripts accept header. But since the Agent updates the devices depending upon the heartbeat rate, therefore if multiple request are made within short time with different accept header then a mixed output of XML and Json is printed out.

**Comment by wsobel** [comment]
I will need to take a look since i don't understand the issues; it should be implemented on a per request basis, not globally.

**Comment by wsobel** [comment]
The accept header should not be an instance variable, it should be per request either passed as a parameter or associated with the current request.

**Comment by wsobel** [comment]
We need to add rapid json to the build as well. Project does not build.

**Comment by wsobel** [comment]
There are no tests.

**Comment by Ghost-script** [comment]
@wsobel , The problem was here https://github.com/mtconnect/cppagent/blob/master/agent/cutting_tool.cpp#L123 , the `mContent` contained the previous `xml` output. so `mContent.empty()` returned `false`, hence the `json` output had `xml` data inbetween and vice-versa . As a fix i removed the check `if (mContent.empty())` , now `mContent` is always updated. Hence, when you switch between `json` and `xml` output the whole document is generated.

About the tests, i tried using https://code.google.com/p/qjsonpath/ but that seemed to have some dependencies on QT files. Also tried writing a json to jsonpath parser using RapidJson but got stuck where arrays objects are referred by their elements eg(`//m:Linear[@name='X']/m:DataItems/m:DataItem@type`).  Do you have any other json to jsonpath parser in mind that can help writing tests?

**Comment by wsobel** [comment]
This has been rewritten in the 1.5 version in development.

**Pull request closed without merging**
