### PR TITLE
Main dev readme file mqtt json ingress update

### PR DESCRIPTION
**Pull request by dwickelhaus**
Update the README.md file with the new MQTT JSON ingress protocol.

### CODE REVIEW

**Comment by wsobel** [comment]
This is all the changes between main-dev and main. We will need to wait until 2.3 is release to merge.

**Comment by dwickelhaus** [comment]
I messed up the pull request.  It was supposed to be merged with main-dev

**Comment by wsobel** [comment]
Figured. I tried to edit, but it jumped back. You can cancel and redo.

**Comment by dwickelhaus** [comment]
Replaced with #402

**Pull request closed without merging**
