### PR TITLE
Mqtt releated version 2

### PR DESCRIPTION
**Pull request by wsobel**
# New Features

* Added new MQTT sink: `Mqtt2Service`
  * Only four topics are used:
    * `MTConnect/Probe/[device]`
    * `MTConnect/Current/[device]`
    * `MTConnect/Sample/[device]`
    * `MTConnect/Assets/[device]`
  * The topics are based on the same concept as the REST interface and provide an efficient way to publish keyframes and deltas similar to video CODECS. The publishing is as follows:
    * **Probe**: Only published when devices are initialized or changed. The probe will only publish the `Device` part of the document JSON.
    * **Current**: The current is published at a slower frequency with all the latest observations for a given device. The current rate is once every 10 seconds and is configurable. Use the `nextSequence` to filter Samples arriving on the Sample Topic. An `MTConnectStreams` document is published in JSON.
    * **Sample**: Published using the given interval (default 500ms) and at the maximum count; if more observations occur, it will immediately publish the rest. If no observations occur for a device in the given interval, it will wait until they arrive. An `MTConnectStreams` document is published in JSON.
    * **Asset**: When created or updated, an asset is published to a separate topic. Only the `Asset` part of the document is published in JSON.

# Bugs Fixed

* Fixed race condition in period filter where multiple observations could be reported for the same period.

### CODE REVIEW

**Review by rajwork9 — APPROVED** [review]
looks good, thank you

**Comment by wsobel** [comment]
Seems to break most builds.

**Comment by wsobel** [comment]
> Seems to break most builds.

@ rajwork9 We should roll back those changes. The issue is they make the opposite assumption that the callback was not called when it should have been. That is why the other builds are failing. The real question is: why is the shared Windows build not calling the callback and only the shared Windows build? 

Is it because in the shared Windows image, the callback is not getting correctly invoked by boost asio, or is it because it is just getting delayed? Or is there something broken in asio in this windows configuration?

I was going to create a Windows intel vm and build it to determine why the callback doesn't get invoked. When I tried the build on ARM w/ a x86_64 build, it worked fine. I have tried a few other combinatorial, but the only way I can think of reproducing is to get as close to the GitHub VM as possible and see if we can reproduce it with the exact build environment. Of course, we need to figure out what size image and other dependencies are, but round-tripping with the CI process is too slow.

**Comment by rajwork9** [comment]
> building on azure VM to get as close to the build actions as possible.

i reverted my changes back to your modification. strange is that amd64 shared:False one was successful before. now its fails as well.

**Comment by wsobel** [comment]
Not sure what’s going on. Building and testing on a VM to check if I can reproduce.

**Pull request merged**
